version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: hulbert
      POSTGRES_PASSWORD: hulbert
      POSTGRES_DB: hulbert
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    env_file:
      - .env.local
    volumes:
      - ../backend/app:/app/app
      - ../domains:/data/domains:ro
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    volumes:
      - ../domains/informatique/02-projects/portfolio/Portfolio/angular-portfolio/dist:/usr/share/nginx/html:ro
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
